distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.7.2:38471'
distributed.diskutils - INFO - Found stale lock file and directory '/glade/scratch/baird/dask-temporary/worker-h9ubj93h', purging
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/process.py", line 173, in _run
    target(*args, **kwargs)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/nanny.py", line 511, in _run
    worker = Worker(*worker_args, **worker_kwargs)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 416, in __init__
    File(path))
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 63, in __init__
    os.mkdir(self.directory)
FileNotFoundError: [Errno 2] No such file or directory: '/glade/scratch/baird/dask-temporary/worker-h7akknq7/storage'
distributed.nanny - WARNING - Worker process 4727 exited with status 1
distributed.nanny - WARNING - Restarting worker
distributed.diskutils - INFO - Found stale lock file and directory '/glade/scratch/baird/dask-temporary/worker-nmm01m24', purging
distributed.worker - INFO -       Start worker at:     tcp://10.148.7.2:39633
distributed.worker - INFO -          Listening to:     tcp://10.148.7.2:39633
distributed.worker - INFO -              nanny at:           10.148.7.2:38471
distributed.worker - INFO -              bokeh at:           10.148.7.2:37214
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.13.4:59754
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         36
distributed.worker - INFO -                Memory:                  100.00 GB
distributed.worker - INFO -       Local Directory: /glade/scratch/baird/dask-temporary/worker-8a6p43po
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.13.4:59754
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      ("('concatenate-37fa85f0bf0d2e8ea95ac9021316bf7c', 0, 0, 11)", (slice(-15, None, None), slice(None, None, None), slice(None, None, None)))
kwargs:    {}
Exception: TypeError('string indices must be integers')

distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      ("('concatenate-37fa85f0bf0d2e8ea95ac9021316bf7c', 0, 0, 11)", (slice(0, 15, None), slice(None, None, None), slice(None, None, None)))
kwargs:    {}
Exception: TypeError('string indices must be integers')

distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      ("('concatenate-37fa85f0bf0d2e8ea95ac9021316bf7c', 1, 1, 3)", (slice(0, 15, None), slice(None, None, None), slice(None, None, None)))
kwargs:    {}
Exception: TypeError('string indices must be integers')

distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      ("('concatenate-37fa85f0bf0d2e8ea95ac9021316bf7c', 0, 5, 1)", (slice(-15, None, None), slice(None, None, None), slice(None, None, None)))
kwargs:    {}
Exception: TypeError('string indices must be integers')

distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      ("('concatenate-37fa85f0bf0d2e8ea95ac9021316bf7c', 0, 5, 1)", (slice(0, 15, None), slice(None, None, None), slice(None, None, None)))
kwargs:    {}
Exception: TypeError('string indices must be integers')

distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      ("('concatenate-37fa85f0bf0d2e8ea95ac9021316bf7c', 1, 5, 5)", (slice(0, 15, None), slice(None, None, None), slice(None, None, None)))
kwargs:    {}
Exception: TypeError('string indices must be integers')

distributed.worker - ERROR - Worker stream died during communication: tcp://10.148.7.39:33527
Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/comm/tcp.py", line 182, in read
    n_frames = yield stream.read_bytes(8)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1607, in gather_dep
    who=self.address)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 2671, in get_data_from_worker
    max_connections=max_connections)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/core.py", line 457, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/comm/tcp.py", line 202, in read
    convert_stream_closed_error(self, e)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/comm/tcp.py", line 129, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: ConnectionResetError: [Errno 104] Connection reset by peer
distributed.worker - INFO - Can't find dependencies for key ('func-overlap-getitem-3cabb2dffd03533d19a98cd929f6f603', 1, 2, 6, 0)
distributed.worker - INFO - Dependent not found: ('getitem-44a31621940ab4f13789030f28e9fd65', 1.1, 2, 6) 0 .  Asking scheduler
=>> PBS: job killed: walltime 3634 exceeded limit 3600
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.7.2:38471'
distributed.nanny - WARNING - Worker process 4733 was killed by unknown signal
distributed.dask_worker - INFO - End worker
