distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.9.173:36486'
distributed.worker - INFO -       Start worker at:   tcp://10.148.9.173:48298
distributed.worker - INFO -          Listening to:   tcp://10.148.9.173:48298
distributed.worker - INFO -              nanny at:         10.148.9.173:36486
distributed.worker - INFO -              bokeh at:         10.148.9.173:41299
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         36
distributed.worker - INFO -                Memory:                  100.00 GB
distributed.worker - INFO -       Local Directory: /var/tmp/pbs.4274824.chadmin1/worker-q9e0iv83
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:  tcp://10.148.13.150:59946
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Failed to put key in memory
Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1356, in transition_executing_done
    self.put_key_in_memory(key, value, transition=False)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1548, in put_key_in_memory
    self.data[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 80, in __setitem__
    self.fast[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 71, in __setitem__
    self.evict()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 90, in evict
    cb(k, v)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 52, in fast_to_slow
    self.slow[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/func.py", line 42, in __setitem__
    self.d[key] = self.dump(value)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 83, in __setitem__
    f.write(v)
OSError: [Errno 28] No space left on device
distributed.core - INFO - Event loop was unresponsive in Worker for 62.54s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 47.85s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - INFO - Can't find dependencies for key ('getitem-d2e9abd9d83a138641d0ed3245d38fe6', 9, 6, 8, 0)
distributed.worker - INFO - Dependent not found: ('func-overlap-getitem-d2e9abd9d83a138641d0ed3245d38fe6', 9, 6, 8, 0) 0 .  Asking scheduler
distributed.worker - INFO - Can't find dependencies for key ('getitem-d2e9abd9d83a138641d0ed3245d38fe6', 9, 6, 8, 0)
distributed.worker - INFO - Dependent not found: ('func-overlap-getitem-d2e9abd9d83a138641d0ed3245d38fe6', 9, 6, 8, 0) 1 .  Asking scheduler
distributed.worker - INFO - Can't find dependencies for key ('func-overlap-getitem-d2e9abd9d83a138641d0ed3245d38fe6', 18, 6, 8, 0)
distributed.worker - INFO - Dependent not found: ('getitem-f5268620eebd5bf42a2ee6365a9b45be', 19, 6, 8) 0 .  Asking scheduler
distributed.worker - INFO - Failed to put key in memory
Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1356, in transition_executing_done
    self.put_key_in_memory(key, value, transition=False)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1548, in put_key_in_memory
    self.data[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 80, in __setitem__
    self.fast[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 71, in __setitem__
    self.evict()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 90, in evict
    cb(k, v)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 52, in fast_to_slow
    self.slow[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/func.py", line 42, in __setitem__
    self.d[key] = self.dump(value)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 83, in __setitem__
    f.write(v)
OSError: [Errno 28] No space left on device
distributed.worker - INFO - Failed to put key in memory
Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 83, in __setitem__
    f.write(v)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1356, in transition_executing_done
    self.put_key_in_memory(key, value, transition=False)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1548, in put_key_in_memory
    self.data[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 80, in __setitem__
    self.fast[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 71, in __setitem__
    self.evict()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 90, in evict
    cb(k, v)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 52, in fast_to_slow
    self.slow[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/func.py", line 42, in __setitem__
    self.d[key] = self.dump(value)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 85, in __setitem__
    f.write(value)
OSError: [Errno 28] No space left on device
distributed.worker - INFO - Can't find dependencies for key ('getitem-d2e9abd9d83a138641d0ed3245d38fe6', 16, 6, 6, 0)
distributed.worker - INFO - Dependent not found: ('func-overlap-getitem-d2e9abd9d83a138641d0ed3245d38fe6', 16, 6, 6, 0) 0 .  Asking scheduler
distributed.worker - INFO - Can't find dependencies for key ('getitem-d2e9abd9d83a138641d0ed3245d38fe6', 16, 6, 6, 0)
distributed.worker - INFO - Dependent not found: ('func-overlap-getitem-d2e9abd9d83a138641d0ed3245d38fe6', 16, 6, 6, 0) 1 .  Asking scheduler
distributed.worker - INFO - Failed to put key in memory
Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 83, in __setitem__
    f.write(v)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1356, in transition_executing_done
    self.put_key_in_memory(key, value, transition=False)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/distributed/worker.py", line 1548, in put_key_in_memory
    self.data[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 80, in __setitem__
    self.fast[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 71, in __setitem__
    self.evict()
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/lru.py", line 90, in evict
    cb(k, v)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/buffer.py", line 52, in fast_to_slow
    self.slow[key] = value
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/func.py", line 42, in __setitem__
    self.d[key] = self.dump(value)
  File "/glade/u/home/baird/miniconda3/envs/pangeo/lib/python3.7/site-packages/zict/file.py", line 85, in __setitem__
    f.write(value)
OSError: [Errno 28] No space left on device
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - Waiting to connect to:  tcp://10.148.13.150:59946
distributed.worker - INFO - Stopping worker at tcp://10.148.9.173:48298
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.9.173:36486'
distributed.dask_worker - INFO - End worker
